### ISSUE TITLE
[Enhancement] Additional kill switch option to keep killswitch on when disconnected

### ISSUE THREAD

**Issue by k0dk0de** [ProtonVPN/linux-cli#157]
**Is your feature request related to a problem? Please describe.**
I would like an additional 'persistent kill switch option', which would leave the kill switch activated when disconnecting via `sudo protonvpn d` and during reconnection via `sudo protonvpn r`. An idea on how to implement it is discussed below.  
I noticed that the absence of this feature from the regular kill switch (which is intended as far as I understand it) has previously been reported in [this "bug report"](https://github.com/ProtonVPN/protonvpn-cli-ng/issues/150). 

**Describe the solution you'd like**
Add an additional configuration when selecting the kill switch to enable a `Persistent Kill Switch`. This will leave the kill switch on when the user reconnects as well as when the user disconnects intentionally from the VPN.

**Describe alternatives you've considered**
Due to the calls to the API which are required currently there's no good alternative to changing the vpnclient code. A first (very) quick and dirty option has successfully been implemented (quite some steps described below were done manually though), however, this is not really an alternative.

**Additional context**
This option would make the connections more secure, however, would end up in slower connects to a wanted servers due to the fact that two connects will be required. 
Furthermore, I will describe a scenario that makes it necessary to initialize the client for the first time from home / from a trusted network (w/o the client already being active... kind of like downloading it).

Potential implementation:
 1. `cli.py: init_cli()`: During initialization create one new file in the `~/.protonvpn-cli` folder with a full openvpn connection (similar to the `connect.ovpn` file that is created when connecting). This file could point to one of the free tier servers and the IP address to this server is saved saved as a configuration variable. 
 1. `cli.py: set_killswitch()`: If the persistent kill switch is enabled, add a line to the iptables allowing the connection to the above saved vpn server. If disabled, remove that line from the iptables (this probably requires some parsing of the iptables since I don't recommend doing it as it is now, i.e., by saving an iptables file and then restoring from file). 
 1. Add a routine in `connection.py` that 
    1. Checks if the Persistent Kill Switch option is activated and 
    2. If it is, connects to the free tier server using the ovpn file saved during the init.
 1. `cli.py: cli()`: In the `connect` and `reconnect` portions of the code, add a call to just mentioned routine, e.g., after `check_init()`. 
 1. `connection.py: openvpn_connect():` If this feature is activated:
    1. Before connecting: Add the new / future server IP to iptables (save the IP somewhere)
    2. Disconnect from the current vpn
    3. Connect to the new server (this will set the killswitch to protonvpn only).
 1. Disconnecting, reconnecting will write the killswitch back to what we had now, i.e, will set to the iptables settings with two servers added, the original (wanted) one, and the "chosen configuration" one from just above. Disconnecting thus needs to remove the latter server in order to keep the iptables clean. 

These are just some ideas, of course proper error handling / checking needs to be implemented such that also a novice user can use this feature. It is a security improvement and should thus be available for everybody.

**Open questions / problems:**
* How does the `utils.py: get_fastest_server()` determine the scores for the fastest servers. Is this dependent on the current location a user is in, i.e., is it dependent on what IP address I have w/o a VPN? If so, this routine probably would become meaningless and should get an additional check and warning if selected.
* Could such a configuration file be delivered with the first client or is the initialization really the best way to do this?
* Should an option be added that lets the user choose a kill switch server if wanted?
* What happens to all the users that have this option selected when that one server that is chosen as the first connection server is undergoing maintenance. Could implement a backup solution...

I'm sure there are many more questions that are still open and need to be discussed. I'd be happy to discuss in detail and would be willing to try and implement the requested feature.

**Comment by snakyjake1** [comment]
This is a huge security/privacy vulnerability:  

1. When I first start my desktop, and haven't connected to the VPN, all my connections are not going through the VPN.

2. It also look like if you try to reconnect to the VPN, the VPN closes, tries to reconnect, and if the VPN connection times-out, you don't have a VPN connection, and the "kill switch" isn't protecting your IP address.

**Comment by k0dk0de** [comment]
I agree that this can be a huge security/privacy vulnerability. This is why I'm proposing to build it into the VPN client. Before doing so I try to follow the [rules](https://github.com/ProtonVPN/linux-cli/blob/master/CONTRIBUTING.md) however and discuss this enhancement first through as an issue. This will surely also make for a better implementation.

**Comment by Rafficer** [comment]
I don't think this is a "huge issue". The Windows, Mac, Android and iOS Clients work just the same afaik and have since their existence without this being a huge issue.

If you want to be sure that every single connection of your desktop goes through a VPN, then your best bet is to run the VPN on your router, otherwise there will always be something not going through.

Lastly, how do you plan to make the firewall routes cleanly persist through reboots for most linux distros?

**Comment by Evernow** [comment]
> Lastly, how do you plan to make the firewall rules cleanly persist through reboots for most linux distros?

Something similar to Mullvad's implementation perhaps? 

https://github.com/mullvad/mullvadvpn-app/pull/581

**Comment by Rafficer** [comment]
What exactly is Mullvad doing? Sorry, I never did anything with Rust.

**Comment by k0dk0de** [comment]
> Lastly, how do you plan to make the firewall rules cleanly persist through reboots for most linux distros?

Very good question that I haven't fully thought about to be honest. @Evernow it would be really interesting indeed to see how Mullvad does it, assuming it is all working there. I don't have any experience with them. 

Most distros have a way of making the iptables stay over a reboot, like `iptables-persistent` on debian. It seems to be a one off setup for many distros to make iptables persistent, could thus also be something to warn the user about and point into the right directions? Just asking. 

> I don't think this is a "huge issue". The Windows, Mac, Android and iOS Clients work just the same afaik and have since their existence without this being a huge issue.

Here I don't really agree: Should have chosen my words more carefully before, if it is "a huge issue" or not is of course in the eye of the beholder. I do think this is something that could be addressed without too much effort, especially on Linux, I don't know enough about other distros to address them. Not sure what to do here? Maybe could at least be made more clear in the documentation what cases the killswitch really kills the connection, and that can be plenty for somebody doing an online investigation who wants to stay safe if the VPN drops.

There are surely many ways of pursuing all of this. For myself this would get side usage, i.e., in the case I don't have my home or my travel router available and need to connect. Then again, that's all the usage I have for a VPN client anyway, otherwise I'm on a VPN connection established by my router.

**Comment by Rafficer** [comment]
> Most distros have a way of making the iptables stay over a reboot, like iptables-persistent on debian. It seems to be a one off setup for many distros to make iptables persistent, could thus also be something to warn the user about and point into the right directions? Just asking.

This is exactly why, in my opinion, this is rather something the user should configure themselves if they want it. When the Kill Switch is set up during connecting, it erases all other rules to make sure that nothing pokes holes in the Kill Switch, and even this doesn't always work on every distro. Making this change permanent only brings problems that ProtonVPN's support team has to sort out because "The Kill Switch broke my whole network setup". And from a support point of view replying with "Well, it warned you about potential issues" isn't really a great idea either, so a warning wouldn't be sufficient.

Some distros use UFW, some use firewalld, some don't use a high-level interface at all, then there's a move coming towards nftables instead of iptables (although nftables still has an iptables compatible interface iirc, so not that much to worry about), then you have to make it work with pre-existing rules... You get the idea. Doing this permanently isn't as easy as chucking all the rules into a persistent file and be done with it.

Can one person do this rather easily on their own for their system? IMO, yes.

Can the CLI do this properly with respects of every system out there? Absolutely not.

I'm sorry, I know that I'm probably a bit harsh here, but I really don't see how this can be properly carried out without breaking systems.

> Maybe could at least be made more clear in the documentation what cases the killswitch really kills the connection

The documentation says that it's for unexpected drops. I don't classify disconnecting, reconnecting or rebooting an unexpected drop in the connection.

> in case your VPN connection is interrupted or cut unexpectedly.

https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#kill-switch

Your internet going down for some time and breaking the tunnel, the openvpn process crashing or in some other way the tunnel getting closed outside of user interaction is what I'd call unexpected. And that's what the Kill Switch protects against.

**Comment by k0dk0de** [comment]
> Can one person do this rather easily on their own for their system? IMO, yes.

Basically DNS lookup would have to be allowed as well though because every connection needs to currently query the API. 

> I'm sorry, I know that I'm probably a bit harsh here, but I really don't see how this can be properly carried out without breaking systems.

No worries, I'm actually very glad about your honest opinion and it makes perfect sense. The persistence problem across different distros is something that I didn't think about about and was really interested in discussing it through before doing anything. 

In fact the more I think about it the easier it seems to be to actually set up an additional iptables rule for the killswitch, especially since the old iptables are written back by the CLI when the VPN is disconnected or a reconnect is initiated.

**Comment by Rafficer** [comment]
How do we proceed with this issue? In my opinion it should be closed, as I don't see this getting added. If you agree, please do so.

**Comment by k0dk0de** [comment]
Agreed
