### ISSUE TITLE
Exception in NM.Client.add_connection_finish() when trying to connect 

### ISSUE THREAD

**Issue by anonymous133** [ProtonVPN/linux-cli#21]
Hi,

 When I try to connect it doesn't connect and doesn't throw an error in the terminal but in the log I found this:

`2021-06-28 17:52:02,224 — nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: NM.Client.add_connection_finish() takes exactly 2 arguments (1 given)
1584 Traceback (most recent call last):
1585   File "/usr/lib/python3.9/site-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
1586     (callback_type_dict[callback_type]["finish_function"])(result)
1587 TypeError: NM.Client.add_connection_finish() takes exactly 2 arguments (1 given)`

Any idea what could be the problem? 

I just installed this client since I was on the older VPN-ng client. So this client has not yet worked for me.

I'm using networkmanager-1.32.0-1

Thank you for your support!

Here are the log files:

[network_manager.service.log](https://github.com/ProtonVPN/linux-cli/files/6727688/network_manager.service.log)
[protonvpn.log](https://github.com/ProtonVPN/linux-cli/files/6727689/protonvpn.log)
[protonvpn-cli.log](https://github.com/ProtonVPN/linux-cli/files/6727690/protonvpn-cli.log)
[protonvpn-dbus-wrapper.log](https://github.com/ProtonVPN/linux-cli/files/6727691/protonvpn-dbus-wrapper.log)

**Comment by calexandru2018** [comment]
Hey @anonymous133 

Thank you for the report. The exceptions that are thrown are mostly due to compatibility with older library, although regardless they should get fixed. Based on the logs that you've provided, I find the problem to be here:
`2021-06-28 17:43:14.587157 <error>  vpn-connection[0x5580ec5ec0e0,17dc36b7-54f5-4b42-848f-3628d668d3ec,"ProtonVPN DE#14",0]: Failed to request VPN secrets #3: No agents were available for this request.`

You could provide more info here about your distro, keyring, etc or you could also contact our support team: https://protonvpn.com/support-form

**Comment by anonymous133** [comment]
Hey @calexandru2018 

I had to add /usr/bin/nm-applet & disown to my startup script and now it works. 

I'm on i3.

Thank you for pointing me in the right direction :)
