### ISSUE TITLE
This app is pure garbage

### ISSUE THREAD

**Issue by CostcoFanboy** [ProtonVPN/linux-cli#95]
I should have checked before spending money how utterly awful the applications are that deviate from the Windows/MacOs status quo. This application is pure garbage and made by people who have absolutely no idea what they're doing.

The whole thing can't even be even be run headless. You need the GUI to login. Yes, a GUI in a *-cli app. 300MB+ GTK/Gnome and X11 dependencies up the wazoo.

From a very quick look, anyone with a minimum of Python experience can tell the author is a junior that just tried his best so I'm not going to blame him, but blame Proton Technologies for how little effort was put into overseeing this project.

The other [linux-app](https://github.com/ProtonVPN/linux-app) is utter garbage too.

Avoid at all cost if you're Linux users. Sticking to Mullvad.

**Comment by a-monospace-odyssey** [comment]
Too true. Even having been "rewarded" with a higher tier of services at some point for being an earlier customer, recently this app has been making a hard case for giving that up just to pay for something that doesn't need me to manually reconnect it *every day* now, an issue which began for seemingly no reason and has only gotten worse, not to mention the myriad of other issues.

genuinely sad to see proton participate in this kafkaesque neglect of paying customers.

**Comment by JCDetwiler** [comment]
I've been working with their customer service about the same manual reconnection issue. Really doesn't feel like it's going anywhere, after they played 120 Questions with me, including a complete reinstallation of this bad Linux client.

Anyone have a good alternative?

**Comment by CostcoFanboy** [comment]
> I've been working with their customer service about the same manual reconnection issue. Really doesn't feel like it's going anywhere, after they played 120 Questions with me, including a complete reinstallation of this bad Linux client.
> 
> Anyone have a good alternative?

Mullvad really. Best Linux VPN client, good speeds and very fair practices.
I just happen to have a lifetime with Windscribe and their cli works fine but if I didn't I'd have went with that. 

What an insane meme this company is.

**Comment by kazin-essen** [comment]
I hear everyone’s pain regarding the Linux app, it is a hatchet job piece of code that hasn’t been updated in years. They took the community created unofficial CLI and slapped some Proton lipstick on it. That being said you may be interested to know that they are working on something. I have been submitting reports, hounding higher and higher levels since October, until reaching a breakthrough in my testing that had them have to act. Here is some of what was said:

_We are aware that Linux users are really privacy-conscious. Different than the other platforms, Linux is an extremely fragmented OS. To support it means supporting a galaxy of combinations among distributions, network subsystems, service subsystems, key stores, and desktop environments. In the last year, we have been working hard to rebuild from the ground up the foundations of a new Linux application.
The new app is designed to be solid, extensible, and future-proof, and will allow our engineers to ship faster new features, like WireGuard, and all those that are presently missing from the current app.
We'll release a preview version as soon as we'll have an MVP you can use daily, so stay tuned!_

Since that follow up conversation in early March, the blog and socials have been updated with announcements that begin to show a return to the roadmap that was set out for 2022: https://proton.me/blog/2022-roadmap As I understand it, the other Proton teams (Mail, Drive, and Calendar) were able to stick to the roadmap for the most part but ProtonVPN was faced with an unprecedented situation last year that required rebalancing —namely, the war in Ukraine, passing of legislation in India and, of course, censorship in Russia. 

That’s all I got. :)

**Comment by JCDetwiler** [comment]
I appreciate the update, I just wish they were the ones making the announcement. To ignore paying customers and abandon official products is unprofessional, at best. Moreover, I've encountered how hard it is to leave one of their subscriptions, since I also use their email and calendar. I got charged another $200 without any warning that my subscription was due to renew.

So not only have they abandoned their own official app, not only have they made it difficult to leave, they also took their new hush project offline into closed-source. To recognize Linux users as a privacy-conscious customer base and then deviate from the company's original values is where I drew the line. I fully recognize the difficulty of world politics here---I don't recognize, however, the blaming on the Linux ecosystem for how they're treating us.

I switched to Mullvad for VPN and it works on Linux just fine. Both cleaner and faster, too.

**Comment by kazin-essen** [comment]
> I appreciate the update, I just wish they were the ones making the announcement. To ignore paying customers and abandon official products is unprofessional, at best. Moreover, I've encountered how hard it is to leave one of their subscriptions, since I also use their email and calendar. I got charged another $200 without any warning that my subscription was due to renew.
> 
> So not only have they abandoned their own official app, not only have they made it difficult to leave, they also took their new hush project offline into closed-source. To recognize Linux users as a privacy-conscious customer base and then deviate from the company's original values is where I drew the line. I fully recognize the difficulty of world politics here---I don't recognize, however, the blaming on the Linux ecosystem for how they're treating us.
> 
> I switched to Mullvad for VPN and it works on Linux just fine. Both cleaner and faster, too.

Gotta say I can’t agree with all your points but it must be incredibly taxing to have such an outlandish experience as that. I personally keep a list of timers and reminders for when any subscription renewal comes up because I see it as my thing to worry about, like my power bill but I recognize that situations differ. Also, they haven’t abandoned anything, after all, there were serious safety issues and access to content concerns as a result of the items that derailed their 2022 roadmap. Arguably, the plight of the Ukraine people, the privacy erosion in India and the censorship in Russia took priority vs. a full rewrite. I’m not saying that they don’t make mistakes, just that in the case here, I don’t chide them. What I cannot excuse is the lack of announcements. That we are of one mind over.

**Comment by CostcoFanboy** [comment]
> Arguably, the plight of the Ukraine people, the privacy erosion in India and the censorship in Russia took priority vs. a full rewrite

I'm not sure why world politics are being mentioned as release frequency has been a problem for ages. Look at their [release schedule](https://github.com/ProtonVPN/linux-cli/releases). There was barely any development before that. 

It's been said time and time and time again. Proton's priority is NOT Linux. Linux is actually dead last after legitimately every single other platform.

Mods were even open about it on Reddit. It goes something like this.

`Windows -> Android -> iOS -> MacOs -> Browser Extensions -> Giving money to orphanages in Uganda -> Linux
`

**Comment by kazin-essen** [comment]
> > Arguably, the plight of the Ukraine people, the privacy erosion in India and the censorship in Russia took priority vs. a full rewrite
> 
> 
> 
> I'm not sure why world politics are being mentioned as release frequency has been a problem for ages. Look at their [release schedule](https://github.com/ProtonVPN/linux-cli/releases). There was barely any development before that. 
> 
> 
> 
> It's been said time and time and time again. Proton's priority is NOT Linux. Linux is actually dead last after legitimately every single other platform.
> 
> 
> 
> Mods were even open about it on Reddit. It goes something like this.
> 
> 
> 
> `Windows -> Android -> iOS -> MacOs -> Browser Extensions -> Giving money to orphanages in Uganda -> Linux
> 
> `
> 
> 
> 
> 

Dude what are you asking me for? It's their reasoning as to why their has been a delay, not mine. Please don't harass me with things I have no control over.

**Comment by CostcoFanboy** [comment]
> Please don't harass me with things I have no control over.

How is this harassing? Are you out of your god damn mind? This is a github issue **I filed** that **YOU** are posting under willingly.

Don't support companies that don't support you.

And if you "don't want to speak about this" with me, don't post under **my issue**. Ridiculous amount of arrogance.

**Comment by kazin-essen** [comment]
> > Please don't harass me with things I have no control over.
> 
> 
> 
> How is this harassing? Are you out of your mind? This is a github issue **I filed** that **YOU** are posting under willingly.
> 
> 
> 
> We are simply done supporting companies that don't support us.
> 
> 
> 
> And if you "don't want to speak about this" with me, don't post under **my issue**. Ridiculous amount of arrogance.

I am so confused, what are you talking about? I haven't responded in here since my reply weeks ago now. I thought I had some good things to say. *scratches head*

**Comment by CostcoFanboy** [comment]
Closing this issue as I moved on to Mullvad and don't feel like dealing with this trolling.

**Comment by kazin-essen** [comment]
> > Please don't harass me with things I have no control over.
> 
> 
> 
> How is this harassing? Are you out of your mind? This is a github issue **I filed** that **YOU** are posting under willingly.
> 
> 
> 
> We are simply done supporting companies that don't support us.
> 
> 
> 
> And if you "don't want to speak about this" with me, don't post under **my issue**. Ridiculous amount of arrogance.

Dude, I am so sorry, so very sorry. My idiotic brother thought it would be funny to post on my behalf and it just so happens that your reply popped into my inbox. I am so deeply upset at him and so sorry for any stress caused to you.

**Comment by kazin-essen** [comment]
> Closing this issue as I moved on to Mullvad and don't feel like dealing with this trolling.

It's not trolling. I am so sincerely sorry dude. I know it's the internet but if you reviewed my replies you would see that a response like that is so out of character. My brother is an a** and I take responsibility for his action. In a place like GitHub, your reputation matters and I am not a troll. Pray, forgive me.

**Comment by CostcoFanboy** [comment]
> Dude, I am so sorry, so very sorry. My idiotic brother thought it would be funny to post on my behalf and it just so happens that your reply popped into my inbox. I am so deeply upset at him and so sorry for any stress caused to you.

"My brother got on my account and typed stupid crap on Github" is probably the most dumb cookie cutter excuse after "my dog ate my homework".

I'm blocking you, this is pathetic and I don't want to waste more time on this.
